name: Terraform platform deployment
on:
  push:
    branches: [feature/AYR-139]
  workflow_dispatch:
    inputs:
      environment:
        description: Env is 
        default: dev

jobs:
  terraform-deployment:
    uses: nationalarchives/da-ayr-gthub-actions/.github/workflows/terraform-enviromements-action.yml@feature/AYR-139
    with:
      environment: ${{ inputs.environment }}
      tf_dir: ${{ inputs.environment }}
#    secrets:
#      token: ${{ secrets.TOKEN }}
