name: Terraform platform deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment you want to deploy to from the dropdown list
        options:
          - dev
jobs:
  terraform-deployment:
    uses: nationalarchives/da-ayr-gthub-actions/.github/workflow/terraform-enviromements-action.yml@feature/AYR-139
    with:
      environment: ${{ inputs.environment }}
      tf_dir: ${{ inputs.environment }}